language: ru

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 2
- name: "LanguageModelFeaturizer"
  model_name: "bert"
  model_weights: "bert-base-cased"
  cache_dir: null
- name: DIETClassifier
  epochs: 1000
  transformer_size: 32
  number_of_transformer_layers: 1
  use_masked_language_model: True
  batch_strategy: "balanced"
  hidden_layers_sizes:
    text: [32]
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 10

policies:
- name: MemoizationPolicy
  max_history: 10
- name: RulePolicy
- name: TEDPolicy
  max_history: 10
  epochs: 10
  constrain_similarities: True
assistant_id: 20241215-120754-equidistant-delay
